



try{
    console.log("Try function starts");
    console.log(x);
}
catch(error){
    console.log(" Error is here:")
}